<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="9" hostname="EPINHYDW0917" failures="1" tests="1" name="Default test" time="0.031" errors="0" timestamp="22 Jun 2021 04:01:24 GMT">
  <testcase classname="com.testngProject.calculator.AppTest" name="testTanValue" time="0.007">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;-6.4053311966462765&amp;gt; but was:&amp;lt;1.0&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<-6.4053311966462765> but was:<1.0>
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failNotEquals(Assert.java:282)
at junit.framework.Assert.assertEquals(Assert.java:101)
at junit.framework.Assert.assertEquals(Assert.java:108)
at com.testngProject.calculator.AppTest.testTanValue(AppTest.java:138)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testTanValue -->
  <testcase classname="com.testngProject.calculator.AppTest" name="testSuValid" time="0.0">
    <ignored/>
  </testcase> <!-- testSuValid -->
  <testcase classname="com.testngProject.calculator.AppTest" name="testCosValue" time="0.0">
    <ignored/>
  </testcase> <!-- testCosValue -->
  <testcase classname="com.testngProject.calculator.AppTest" name="testSinValue" time="0.0">
    <ignored/>
  </testcase> <!-- testSinValue -->
  <testcase classname="com.testngProject.calculator.AppTest" name="testNumisPositive" time="0.0">
    <ignored/>
  </testcase> <!-- testNumisPositive -->
  <testcase classname="com.testngProject.calculator.AppTest" name="testMulValid" time="0.0">
    <ignored/>
  </testcase> <!-- testMulValid -->
  <testcase classname="com.testngProject.calculator.AppTest" name="testSubValid" time="0.0">
    <ignored/>
  </testcase> <!-- testSubValid -->
  <testcase classname="com.testngProject.calculator.AppTest" name="testSqrtValid" time="0.0">
    <ignored/>
  </testcase> <!-- testSqrtValid -->
  <testcase classname="com.testngProject.calculator.AppTest" name="testDivValid" time="0.0">
    <ignored/>
  </testcase> <!-- testDivValid -->
  <testcase classname="com.testngProject.calculator.AppTest" name="testSumValid" time="0.0">
    <ignored/>
  </testcase> <!-- testSumValid -->
</testsuite> <!-- Default test -->
